// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-hwoIJg0UKl6OQtrQxcKmbJAmUOqABQU',
    appId: '1:127153959622:web:1d5695cd44913a30439dc7',
    messagingSenderId: '127153959622',
    projectId: 'storytelling-app-820a5',
    authDomain: 'storytelling-app-820a5.firebaseapp.com',
    storageBucket: 'storytelling-app-820a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuGpFPRzFDqa7JoMvRnfCg33X0I7Fi6-A',
    appId: '1:127153959622:android:d5ecc29aa464f187439dc7',
    messagingSenderId: '127153959622',
    projectId: 'storytelling-app-820a5',
    storageBucket: 'storytelling-app-820a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcwjtgWZNlsfCFYMNhJVAH8GlJT_vCEf4',
    appId: '1:127153959622:ios:6285ef507f35f5e5439dc7',
    messagingSenderId: '127153959622',
    projectId: 'storytelling-app-820a5',
    storageBucket: 'storytelling-app-820a5.appspot.com',
    androidClientId: '127153959622-69plup2oeu4qkrm12gm78b8mv91pkp01.apps.googleusercontent.com',
    iosClientId: '127153959622-kia0ougr01ub3p3j3o2s6oj5bmtafkqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.storytellingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcwjtgWZNlsfCFYMNhJVAH8GlJT_vCEf4',
    appId: '1:127153959622:ios:b6fbf72cebc2f138439dc7',
    messagingSenderId: '127153959622',
    projectId: 'storytelling-app-820a5',
    storageBucket: 'storytelling-app-820a5.appspot.com',
    androidClientId: '127153959622-69plup2oeu4qkrm12gm78b8mv91pkp01.apps.googleusercontent.com',
    iosClientId: '127153959622-plkctc4orsen7rgi6hp385je4e773n48.apps.googleusercontent.com',
    iosBundleId: 'com.example.storytellingApp.RunnerTests',
  );
}
